#!/bin/sh
set -e

# Hook for building live images
#
# This script is run in the built chroot after all packages are installed,
# before it is packed into a squashfs. This is where you can apply extra tweaks
# to the live system.

#12.04
apt-get --yes --force-yes install python-software-properties 

#12.10
apt-get --yes --force-yes install software-properties-common 

#ppa-ji
add-apt-repository ppa:libreoffice/ppa -y
add-apt-repository ppa:otto-kesselgulasch/gimp -y
add-apt-repository ppa:janez-troha/ubuntu-si-welcome -y
add-apt-repository ppa:tualatrix/ppa -y

#Updated PPA
apt-get --yes --force-yes update
apt-get --yes --force-yes upgrade
apt-get --yes --force-yes dist-upgrade

#Slovenjenje
apt-get --yes --force-yes install firefox-locale-sl thunderbird-locale-sl hyphen-sl language-pack-gnome-sl language-pack-gnome-sl-base language-pack-sl libreoffice-help-sl libreoffice-l10n-sl myspell-sl
apt-get --yes --force-yes install ubuntu-si-welcome 
apt-get --yes --force-yes install ubuntu-tweak
apt-get --yes --force-yes install ubuntu-si-welcome

#Neuporabno
apt-get purge gwibber --yes --force-yes
apt-get --yes --force-yes autoremove --purge
apt-get --yes --force-yes clean

echo "Europe/Ljubljana" > /etc/timezone
gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults --type string --set "/desktop/gnome/interface/gtk_theme" "Radiance"

#Ubuntu vodič

wget http://dk.fdv.uni-lj.si/ek/pdfs/ek_kovacic_2010_Linux_na_namizju.pdf -O "/usr/share/example-content/Linux na namizju.pdf"
wget --no-check-certificate https://www.ubuntu.si/wordpress/wp-content/uploads/ubuntu-manual-sl-final-1204.pdf -O "/usr/share/example-content/Kako začeti z Ubuntujem.pdf"

#Chome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list

#fix https://github.com/dz0ny/ubuntu-si/issues/1
sed -i 's/\"//g' /usr/lib/firefox/distribution/distribution.ini
