#!/bin/sh
set -e

# Hook for building live images
#
# This script is run in the built chroot after all packages are installed,
# before it is packed into a squashfs. This is where you can apply extra tweaks
# to the live system.

#12.04
apt-get --yes --force-yes install python-software-properties 

#12.10
apt-get --yes --force-yes install software-properties-common 

#ppa-ji
add-apt-repository ppa:libreoffice/ppa -y
add-apt-repository ppa:otto-kesselgulasch/gimp -y

#Updated PPA
apt-get --yes --force-yes update
apt-get --yes --force-yes upgrade

#Neuporabno
apt-get purge gwibber --yes --force-yes

#Slovenjenje
apt-get --yes --force-yes install firefox-locale-sl thunderbird-locale-sl hyphen-sl language-pack-gnome-sl language-pack-gnome-sl-base language-pack-sl libreoffice-help-sl libreoffice-l10n-sl myspell-sl
apt-get --yes --force-yes autoremove --purge
apt-get --yes --force-yes clean

echo "Europe/Ljubljana" > /etc/timezone
gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults --type string --set "/desktop/gnome/interface/gtk_theme" "Radiance"

#Ubuntu vodič
mkdir -p /home/ubuntu/Desktop/
wget http://dk.fdv.uni-lj.si/ek/pdfs/ek_kovacic_2010_Linux_na_namizju.pdf "/home/ubuntu/Desktop/Linux na namizju.pdf"
wget https://www.ubuntu.si/wordpress/wp-content/uploads/ubuntu-manual-sl-final-1204.pdf "/home/ubuntu/Desktop/Kako začeti z Ubuntujem.pdf"
chown ubuntu:ubuntu /home/ubuntu/ -R

